# Generated by Django 4.1.7 on 2023-03-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sale'), ('PL', 'Products Loss'), ('PE', 'Products Entry')], max_length=2)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Makers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('image', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/a/ae/Olympic_flag.jpg', null=True)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=5)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.makers')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varProduct', models.FloatField()),
                ('money', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.event')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.person'),
        ),
    ]
